export default {
	SET_PLAYERS_DATA: "SET_PLAYERS_DATA",
    
	GET_CATEGORIES_IDS_STARTED: "GET_CATEGORIES_IDS_STARTED",
	GET_CATEGORIES_IDS_SUCCESS: "GET_CATEGORIES_IDS_SUCCESS",
	GET_CATEGORIES_IDS_ERROR: "GET_CATEGORIES_IDS_ERROR",

	GET_QUESTIONS_STARTED: "GET_QUESTIONS_STARTED",
	GET_QUESTIONS_SUCCESS: "GET_QUESTIONS_SUCCESS",
	GET_QUESTIONS_ERROR: "GET_QUESTIONS_ERROR",
    
	STORE_PLAYERS: "STORE_PLAYERS",
	ADD_PLAYER_NAME: "ADD_PLAYER_NAME",
	SET_SELECTED_CATEGORY: "SET_SELECTED_CATEGORY",
	SET_SELECTED_DIFFICULTY: "SET_SELECTED_DIFFICULTY",
	TOGGLE_CATEGORIES: "TOGGLE_CATEGORIES",
}